// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xW9z80pmFPIvHvsO3dKQ_A_4RAJ6HmE',
    appId: '1:1092315055213:web:bbd8bc45c14b294511eb64',
    messagingSenderId: '1092315055213',
    projectId: 'mosen-portfolio',
    authDomain: 'mosen-portfolio.firebaseapp.com',
    storageBucket: 'mosen-portfolio.appspot.com',
    measurementId: 'G-1WCWL65FYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-g81mpavWiAvdNwSPKH5uPKXuBlc35M',
    appId: '1:1092315055213:android:ac50b6fb563ed6d411eb64',
    messagingSenderId: '1092315055213',
    projectId: 'mosen-portfolio',
    storageBucket: 'mosen-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSXc1AIhYxoNOyd5izfhvTqsbiW2wYdYk',
    appId: '1:1092315055213:ios:bc1b76b7ee88d81611eb64',
    messagingSenderId: '1092315055213',
    projectId: 'mosen-portfolio',
    storageBucket: 'mosen-portfolio.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSXc1AIhYxoNOyd5izfhvTqsbiW2wYdYk',
    appId: '1:1092315055213:ios:bc1b76b7ee88d81611eb64',
    messagingSenderId: '1092315055213',
    projectId: 'mosen-portfolio',
    storageBucket: 'mosen-portfolio.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xW9z80pmFPIvHvsO3dKQ_A_4RAJ6HmE',
    appId: '1:1092315055213:web:6043352dc8e4554e11eb64',
    messagingSenderId: '1092315055213',
    projectId: 'mosen-portfolio',
    authDomain: 'mosen-portfolio.firebaseapp.com',
    storageBucket: 'mosen-portfolio.appspot.com',
    measurementId: 'G-QT2YXZFEYZ',
  );
}
